apiVersion: v1
data:
  db: restaurant
  url: database
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-03T17:28:49Z"
  name: rest-configmap
  namespace: inovola
  resourceVersion: "22713345"
  uid: cda29dba-6363-4f80-8824-e6527e275519
